version: "3"

services:
  pgdb:
    container_name: pumpkin-db
    image: postgres:16
    restart: no
    volumes:
      - ${PG_VOLUME}
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
